version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: calc_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: calc_backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/calculator_db
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: calc_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
